version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/meghrathod/kabootar"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "prettier"