server {
    listen 80;

    server_name _;

    location / {
        proxy_pass http://localhost:$PORT ; # Ensure this matches the port your Go app listens on
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}